### DISCUSSION TITLE
How to install LsHallo ets2 dedicated convoy server

### DISCUSSION THREAD

**Discussion by RubiksRoleplay** [LsHallo/ets2-dedicated-convoy-server#15] [General]
Hi LsHallo 
I have a dedicated server where i have allready my drivershub and website and discord bot and api,s running on it next step is installing a convoy mode server for ETS2.

Could you pleas explain me how to install this on ubunto 22.04 casue i dont want to damage anything what i have installed allready on my dedicated server your help would be very appriciated :) thanks in advanced.

**Comment by LsHallo** [comment]
I'm going to assume you don't have docker installed already?
1a. Install docker the lazy way (choose 1a or 1b):
`curl https://get.docker.com | bash`
1b. Install docker manually: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-22-04
Doing step 1 and 2 of the digitalocean tutorial is enough.
1.1. Verify that docker is working
`docker run --rm hello-world`

2. Create a folder where ETS server will live and change into it
`cd ~ && mkdir ets-server &&  cd ets-server`
3. Create a docker compose file inside the folder
`nano docker-compose.yml`
4. Paste the following
```yaml
version: '3'

services:
  ets2:
    image: lshallo/ets2-convoy-server
    container_name: ets2-server
    restart: unless-stopped
    network_mode: host
    tty: true
    environment:
      - "ETS_SERVER_UPDATE_ON_START=true"
      - "ETS_SERVER_NAME=My Server"
      - "ETS_SERVER_DESCRIPTION=My Server"
      - "ETS_SERVER_SERVICE_NO_COLLISION=false"
      - "ETS_SERVER_LOGON_TOKEN=[your ets2 logon token]"
      - "ETS_SERVER_MODERATORS=[add your steam id] (you could use https://www.steamidfinder.com/)"
```
Replace the ets2 logon token with the token you get on https://steamcommunity.com/dev/managegameservers.
For ETS use AppID 227300, for ATS use AppID 270880.
You will be given a hexadecimal token that you need to paste in the docker-compose.yml.
This token will expire from time to time and you will get error 106 when you look into the logs of the server.
Just get a new token using the same method when applicable.

If you want to be able to use console commands on the server you need to add yourself to the moderator list.
Get your steam64 id (dec) on https://www.steamidfinder.com/ and paste ist where indicated.

Save the docker-compose file.

5. Open ports in your firewall
Make sure `27015:27016/udp` and `27015:27016/tcp` are open in your firewall.

6. Start your server
`docker compose up -d` (needs to be executed in the ets-server directory)

7. Watch the server logs
  `docker compose logs -f` (needs to be executed in the ets-server directory)
  You will see steamcmd downloading the server.
  Afterwards you need to look for the line `[MP] Session search id: 3870gaozsdg782gaszdgasd/101`.
  Copy the search ID into the search box in game and your server should show up.

  It is also possible that you can find it by the name but that is less reliable.
