### ISSUE TITLE
BUG: Server wont start - infinite log loop - steamservice.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jamess60** [LsHallo/ets2-dedicated-convoy-server#14]
Hi

I just deployed a server with this container. The server does not start and the logs infinite loop. 
Any ideas? - Looks like the server binary isnt going where it should do. 

Compose:
```
    ets2-promods-priv:
        image: ghcr.io/lshallo/ets2-convoy-server
        container_name: ets2-promods-priv
        restart: always
        tty: true
        network_mode: host
        volumes:
            - /containers/v-cont-02/data/ets2/promods/server-data:/app
            - /containers/v-cont-02/data/ets2/promods/custom:/home/steam/.local/share/Euro Truck Simulator 2
        environment:
            - ETS_SERVER_UPDATE_ON_START=true
            - ETS_SERVER_NAME=CENSORED
            - ETS_SERVER_DESCRIPTION=CENSORED
            - ETS_SERVER_WELCOME_MESSAGE=CENSORED
            - ETS_SERVER_PASSWORD=CENSORED
            - ETS_SERVER_MAX_PLAYERS=8
            - ETS_SERVER_PORT=27015
            - ETS_SERVER_QUERY_PORT=27016
            - ETS_SERVER_PLAYER_DAMAGE=false
            - ETS_SERVER_TRAFFIC=false
            - ETS_SERVER_HIDE_IN_COMPANY=false
            - ETS_SERVER_HIDE_COLLIDING=false
            - ETS_SERVER_FORCE_SPEEDLIMITER=false
            - ETS_SERVER_MODS_OPTIONING=true
            - ETS_SERVER_SERVICE_NO_COLLISION=true
            - ETS_SERVER_NAME_TAGS=true
            - ETS_SERVER_SHOW_SERVER=true
            - ETS_SERVER_MODERATORS=CENSORED
            - ETS_SERVER_LOGON_TOKEN=CENSORED
```

I get the following log output:
```

[INFO]: Starting server...
bash: line 1: /app/bin/linux_x64/eurotrucks2_server: No such file or directory
[INFO]: Writing config file...
[INFO]: Config file written.
[INFO]: Updating ETS Server...
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Downloading update (0 of 59,782 KB)...
[  0%] Downloading update (532 of 59,782 KB)...
[  0%] Downloading update (3,397 of 59,782 KB)...
[  5%] Downloading update (5,900 of 59,782 KB)...
[  9%] Downloading update (7,630 of 59,782 KB)...
[ 12%] Downloading update (9,419 of 59,782 KB)...
[ 15%] Downloading update (11,201 of 59,782 KB)...
[ 18%] Downloading update (12,676 of 59,782 KB)...
[ 21%] Downloading update (14,175 of 59,782 KB)...
[ 23%] Downloading update (15,833 of 59,782 KB)...
[ 26%] Downloading update (17,400 of 59,782 KB)...
[ 29%] Downloading update (18,963 of 59,782 KB)...
[ 31%] Downloading update (20,593 of 59,782 KB)...
[ 34%] Downloading update (22,092 of 59,782 KB)...
[ 36%] Downloading update (22,641 of 59,782 KB)...
[ 37%] Downloading update (25,409 of 59,782 KB)...
[ 42%] Downloading update (27,059 of 59,782 KB)...
[ 45%] Downloading update (28,467 of 59,782 KB)...
[ 47%] Downloading update (30,320 of 59,782 KB)...
[ 50%] Downloading update (31,887 of 59,782 KB)...
[ 53%] Downloading update (33,481 of 59,782 KB)...
[ 56%] Downloading update (35,171 of 59,782 KB)...
[ 58%] Downloading update (36,626 of 59,782 KB)...
[ 61%] Downloading update (38,038 of 59,782 KB)...
[ 63%] Downloading update (39,428 of 59,782 KB)...
[ 65%] Downloading update (40,720 of 59,782 KB)...
[ 68%] Downloading update (41,559 of 59,782 KB)...
[ 69%] Downloading update (42,355 of 59,782 KB)...
[ 70%] Downloading update (43,051 of 59,782 KB)...
[ 72%] Downloading update (44,025 of 59,782 KB)...
[ 73%] Downloading update (44,872 of 59,782 KB)...
[ 75%] Downloading update (45,615 of 59,782 KB)...
[ 76%] Downloading update (46,530 of 59,782 KB)...
[ 77%] Downloading update (47,298 of 59,782 KB)...
[ 79%] Downloading update (48,276 of 59,782 KB)...
[ 80%] Downloading update (49,115 of 59,782 KB)...
[ 82%] Downloading update (49,942 of 59,782 KB)...
[ 83%] Downloading update (50,686 of 59,782 KB)...
[ 84%] Downloading update (51,557 of 59,782 KB)...
[ 86%] Downloading update (52,451 of 59,782 KB)...
[ 87%] Downloading update (53,290 of 59,782 KB)...
[ 89%] Downloading update (54,026 of 59,782 KB)...
[ 90%] Downloading update (54,821 of 59,782 KB)...
[ 91%] Downloading update (55,831 of 59,782 KB)...
[ 93%] Downloading update (56,153 of 59,782 KB)...
[ 93%] Downloading update (56,710 of 59,782 KB)...
[ 94%] Downloading update (57,565 of 59,782 KB)...
[ 96%] Downloading update (58,460 of 59,782 KB)...
[ 97%] Downloading update (59,295 of 59,782 KB)...
[ 99%] Downloading update (59,782 of 59,782 KB)...
[100%] Download complete.
[----] Installing update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
tid(25) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 14.24 (30408704 / 213615093)
 Update state (0x61) downloading, progress: 38.25 (81705475 / 213615093)
 Update state (0x61) downloading, progress: 54.72 (116881588 / 213615093)
 Update state (0x61) downloading, progress: 68.91 (147198984 / 213615093)
 Update state (0x61) downloading, progress: 80.58 (172137557 / 213615093)
 Update state (0x61) downloading, progress: 94.11 (201032181 / 213615093)
Success! App '1948160' fully installed.
[INFO]: Update done.
[INFO]: Starting server...
bash: line 1: /app/bin/linux_x64/eurotrucks2_server: No such file or directory
[INFO]: Writing config file...
[INFO]: Config file written.
[INFO]: Updating ETS Server...
tid(13) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '1948160' already up to date.
[INFO]: Update done.
[INFO]: Starting server...
bash: line 1: /app/bin/linux_x64/eurotrucks2_server: No such file or directory
[INFO]: Writing config file...
[INFO]: Config file written.
[INFO]: Updating ETS Server...
tid(13) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK

```
