### ISSUE TITLE
Banlist is deleted

### ISSUE THREAD

**Issue by Revoshell** [LsHallo/ets2-dedicated-convoy-server#19]
The question is in the header itself. When you restart the containers using (docker compose down && docker compose up -d), the file with bans is deleted. It must not be deleted.

**Comment by LsHallo** [comment]
I think you expect to much from docker. When you run docker compose down it will delete all files inside the container. If you did not mount `/home/steam/.local/share/Euro Truck Simulator 2` on your local file system all files will be deleted.
You need to mount `/home/steam/.local/share/Euro Truck Simulator 2` using volume mounts to keep the banlist when using `docker compose down` like this:
```yaml
[...]
    volumes:
      - "/opt/ets2-server/:/home/steam/.local/share/Euro Truck Simulator 2"
[...]
```
After you make this change your banlist might be deleted once more but after that it should stay in place.
If you want to view the current banlist before overwriting it again you can exec into the container and view it that way:
`docker compose exec ets2-server bash`
There you can navigate to `/home/steam/.local/share/Euro Truck Simulator 2` and view all server settings files. Please note that server_settings.sii will be overwritten by the startup script whatever you do with the file. You can disable this behaviour using env variables.

**Comment by LsHallo** [comment]
Yes you can run multiple servers.
Just paste the same service config in your docker compose again. You will have to rename the service and change the port using `ETS_SERVER_PORT` environment variable.
Then it should work fine.

So it could look like this:
```yaml
services:
  ets2-server1: # <- change for each server
    image: lshallo/ets2-convoy-server
    container_name: ets2-server1 # <- change for each server
    restart: unless-stopped
    tty: true
    network_mode: host
    volumes:
     - "/opt/ets2-server/save-data:/home/steam/.local/share/Euro Truck Simulator 2"
    environment:
      - "ETS_SERVER_UPDATE_ON_START=true"
      - "ETS_SERVER_NAME=My Server 1" # <- change for each server
      - "ETS_SERVER_DESCRIPTION=My server description 1" 
      - "ETS_SERVER_WELCOME_MESSAGE=Welcome to my server!"
      - "ETS_SERVER_PASSWORD=abc123"
      - "ETS_SERVER_MAX_PLAYERS=8"
      - "ETS_SERVER_PORT=27015" # <- change for each server
      - "ETS_SERVER_QUERY_PORT=27016" # <- change for each server
      # more variables...

  ets2-server2:
    image: lshallo/ets2-convoy-server
    container_name: ets2-server2
    restart: unless-stopped
    tty: true
    network_mode: host 
    volumes:
     - "/opt/ets2-server/save-data:/home/steam/.local/share/Euro Truck Simulator 2"
    environment:
      - "ETS_SERVER_UPDATE_ON_START=true"
      - "ETS_SERVER_NAME=My Server 2"
      - "ETS_SERVER_DESCRIPTION=My server description 2"
      - "ETS_SERVER_WELCOME_MESSAGE=Welcome to my server!"
      - "ETS_SERVER_PASSWORD=abc123"
      - "ETS_SERVER_MAX_PLAYERS=8"
      - "ETS_SERVER_PORT=27017" # <- changed here
      - "ETS_SERVER_QUERY_PORT=27018" # <- changed
      # more variables...
```
