### ISSUE TITLE
cant start - eurotrucks2_server: No such file

### ISSUE THREAD

**Issue by kaaac** [LsHallo/ets2-dedicated-convoy-server#20]
Hello! Few months ago i was using this way to host convoy with success.
Now i want to do it again, but can't start. below last part of logs:

```
ets2-server  | [INFO]: Starting server...
ets2-server  | bash: line 1: /app/bin/linux_x64/eurotrucks2_server: No such file or directory
ets2-server exited with code 0

```

**Comment by LsHallo** [comment]
Hello,
thank you for your report.
How do your start your container?
Can your share your whole run config (docker-compose.yml)?
My first guess would be: file system / permission issues with the mount.
The user changed from root (uid 0) to steam (uid 1000). So you can try `chown -R 1000:1000 /mount/directory/of/container/files`.

Also try to start this minimal config and report the logs here:
```yaml
services:
  ets2-server:
    image: lshallo/ets2-convoy-server
    container_name: ets2-server
    restart: unless-stopped
    tty: true
    network_mode: host
    environment:
      - "ETS_SERVER_UPDATE_ON_START=true"
      - "ETS_SERVER_NAME=My Server (Test)"
      - "ETS_SERVER_DESCRIPTION=My server description"
      - "ETS_SERVER_WELCOME_MESSAGE=Welcome to my server!"
      - "ETS_SERVER_PASSWORD=123"
      - "ETS_SERVER_MAX_PLAYERS=8"
```

**Comment by kaaac** [comment]
Thank you for a quick reply.

I tried minimal config and it started without issues, also without changes to any permissions - obviously in minimal config there was no mount.

I don't have steam user on my linux, this uuid have another user on this linux vm.

Below is my config:

```
version: "3"

services:
  ets2-server:
    image: lshallo/ets2-convoy-server
    container_name: ets2-server
    restart: unless-stopped
    tty: true
    network_mode: host
    volumes:
      - "/opt/docker/ets2/game-data:/app" # server data
      - "/opt/docker/ets2/save-data:/root/.local/share/Euro Truck Simulator 2"  # Only needed when using custom server_packages.sii and server_packages.dat
    environment:
      - "ETS_SERVER_UPDATE_ON_START=true"
      - "ETS_SERVER_NAME=KaacServer"
      - "ETS_SERVER_DESCRIPTION=Zapraszam!!"
      - "ETS_SERVER_WELCOME_MESSAGE=No witam serdecznie!"
      - "ETS_SERVER_PASSWORD=Redacted"
      - "ETS_SERVER_MAX_PLAYERS=8"
      - "ETS_SERVER_PORT=27015"
      - "ETS_SERVER_QUERY_PORT=27016"
      - "ETS_SERVER_LOGON_TOKEN=Redacted"

```

**Comment by LsHallo** [comment]
That your host system has a different user with the same ID should not create any issues. Just chown the folder on the host with UID 1000. It might display a different username on the host but the ID is the deciding factor.

For a quick solution you could just comment out the first volume mount. It only contains the server files that can be downloaded again easily. No need really to mount it other to ensure server files survive docker compose down (which you might want with slow internet speeds). Not mounting also helps with permission issue when I change the underlying steamcmd image and don't think about permission consequences ;)

If you want to investigate permissions issues further please execute the following command:
`docker compose exec ets2-server bash -c 'ls -lan /app'`

Also your second mount now points to the incorrect location. The config directory has moved to `/home/steam/.local/share/Euro Truck Simulator 2` with v0.3. I really need to improve the handling of breaking changes...

**Comment by kaaac** [comment]
Fix mouting path and correct user uuid/guid solved this issue.

But now this server should be searchable by convoy search? as i remember i did not mapped and open any port from container/host at previous install... but now i can't find server in search

**Comment by LsHallo** [comment]
Yeah to get search to work is a bit tricky and I don't have any good troubleshooting tips for that. It's not transparent what the criteria are to be available in search.

You could try to change your logon token if you have not refreshed it in the last few days. Since you are already using host networking mode you don't need to add any ports to your docker-compose config for it to work. But you might need to configure the firewall of your VM and or Hypervisor to allow traffic on the ports specified (27015, 27016 tcp + udp).

**Comment by LsHallo** [comment]
I just tried with my server (host networking, ufw ports 27015:27016/tcp and 27015:27016/udp opened, logon token provided) and could find my server without issue. It seems to be some kind of firewall in the way in your case.

**Comment by kaaac** [comment]
Ohh ok, I'll check firewall and nat at previous install and try again tomorrow. 
Also at previous step I regenerated token due to 106 error just not mentioned about it.
Thank you! I'll try with firewall and let you know.

In meantime, maybe you know, is there possibility to extract info about server status and connected players outside container? I'm thinking about pushing this info later to my Home Assistant server and finally display those info there :)

**Comment by LsHallo** [comment]
Hello,

any luck with your server configuration and searchability?
If you don't mind I would close this issue since your problem seems to be resolved.

**Comment by kaaac** [comment]
Yes yes, sorry for delay! Firewall changes fixed issue! Thank you for that reminder!

We can close this issue.

Do you have any idea to expose info from container about session and players?

**Comment by kaaac** [comment]
Hello again!
Can we reopen issue or should i create new one?

I have again issue with server visibility using search by text.

Changes on my side - Server Name, Description, server_packages.

There is output from startup, maybe you can find some useful info from this:
https://gist.github.com/kaaac/baa9645b37cd3d41eb030f6155de6bd1

also i tried to switch compose config

removed line network_mode - added ports mappings.

```
version: "3"

# You can freely choose which server to run. They don't depend on one another.
# This file gives an example config for both games.

services:
  ets2-server:
    image: lshallo/ets2-convoy-server
    # image: ghcr.io/lshallo/ets2-convoy-server # GitHub container registry
    container_name: ets2-server
    restart: unless-stopped
    user: 1000:1000
    tty: true
    #network_mode: host
    ports:
      - "27015:27015"
      - "27016:27016"
      - "27015:27015/udp"
      - "27016:27016/udp"
    volumes:
      - "/opt/docker/ets2/game-data:/app" # server data
      - "/opt/docker/ets2/save-data:/home/steam/.local/share/Euro Truck Simulator 2" 
    environment:
      - "ETS_SERVER_UPDATE_ON_START=true"
      - "ETS_SERVER_NAME=DAD Logistics 01 By Kaac"
      - "ETS_SERVER_DESCRIPTION=Zapraszam!!"
      - "ETS_SERVER_WELCOME_MESSAGE=No witam serdecznie!"
      - "ETS_SERVER_PASSWORD=Redacted"
      - "ETS_SERVER_MAX_PLAYERS=8"
      - "ETS_SERVER_PORT=27015"
      - "ETS_SERVER_QUERY_PORT=27016"
      - "ETS_SERVER_LOGON_TOKEN=Redacted"

```

ufw config (no changes since it was working well)

```

Status: active

To                         Action      From
--                         ------      ----
        
...              
27015/tcp                  ALLOW       Anywhere                  
27015/udp                  ALLOW       Anywhere                  
27016/udp                  ALLOW       Anywhere                  
27016/tcp                  ALLOW       Anywhere                  
...             
27015/tcp (v6)             ALLOW       Anywhere (v6)             
27015/udp (v6)             ALLOW       Anywhere (v6)             
27016/udp (v6)             ALLOW       Anywhere (v6)             
27016/tcp (v6)             ALLOW       Anywhere (v6)

```

I also tried to generate new LOGON_TOKEN, all from above did

Thats all i think... Any clue?

**Comment by LsHallo** [comment]
Yes have a look what is in docker-compose.yml right above port mapping:
> if you want to join via direct join token (displayed in logs on startup) you can use port mapping
> the game will not appear in server list because the server can't determine the external IP

and whats written behind `network_mode: host`:
> important to make game appear in server list

So first step would be to use host networking mode. And logon token is required for it to be visible in search.

To add:
I still don't know which criteria all need to be fulfilled for it to be visible. I don't have official statements from SCS regarding that. So it's really hard to tell what's required and what is not. The config in the docker compose is what I used on my VPS which has a public IP and is not behind NAT. If you are it might be even harder to get it to show up. I don't know how it's evaluated.

**Comment by kaaac** [comment]
Thanks!

I tried also with network_mode: host (that state was when was  working in the past),
Logon token - is there.
Public IP - is there.

So it seems to be undiscovered so far what is wrong....
I thought maybe there is some indicator in output log what could i miss.

Docker image is newest? (on my side i pulled latest).

It is not urgent, but can you confirm that you have now visible server (not added to favorites) ?


Irrelevant discovery:

1. Search convoy by ID
2. Add to favorites (star button)
3. Change ServerName
4. Convoy no longer able to find by ID or Name or favorite

Workaround:
1. go back to old ServerName
2. Now visible as favorite - so unmark as favorite
Pretty bad behaviour - users who have saved as favorite can't find this server anymore

2nd workaround: Generate new server logon token - this way newly generated server have new search ID

**Comment by LsHallo** [comment]
I just tried again and it works fine for me:
```yaml
services:
  ets2:
    image: lshallo/ets2-convoy-server:latest
    container_name: ets2
    restart: unless-stopped
    network_mode: host
    tty: true
    environment:
      - "ETS_SERVER_UPDATE_ON_START=true"
      - "ETS_SERVER_NAME=LsHallos Server"
      - "ETS_SERVER_DESCRIPTION=My Server"
      - "ETS_SERVER_PASSWORD=321"
      - "ETS_SERVER_MAX_PLAYERS=8"
      - "ETS_SERVER_SERVICE_NO_COLLISION=false"
      - "ETS_SERVER_LOGON_TOKEN=well_your_own_i_guess"
      - "ETS_SERVER_MODERATORS=76561198045400732"
```

Accompanying screenshots: https://imgur.com/a/Am9bhkX
Freshly pulled my image just now.

Server is still online so you can try yourself.
