### ISSUE TITLE
Not loading mods

### ISSUE THREAD

**Issue by BlackRose01** [LsHallo/ets2-dedicated-convoy-server#7]
Hello again :)

now I try to load my local mods/maps but the game will not load them. The mods/server_packages will be synced via MEGA. I also looked into the container and the mods/server_packages were available and have the same user permissions like the other files.

KR,
BlackRose01

## Docker-Compose
```yaml
version: '3'

services:
  ets2:
    user: "1000"
    build:
      context: steam-fix
    container_name: 'ETS2'
    restart: on-failure
    tty: true
    network_mode: host
    volumes:
      - "/opt/ets2/server_data:/app"
      - "/opt/ets2/game_data:/root/.local/share/Euro Truck Simulator 2"
      - "/opt/ets2/mods:/root/.local/share/Euro Truck Simulator 2/mod"
      - "/opt/ets2/server_packages.sii:/root/.local/share/Euro Truck Simulator 2/server_packages.sii"
      - "/opt/ets2/server_packages.dat:/root/.local/share/Euro Truck Simulator 2/server_packages.dat"
    environment:
      - "ETS_SERVER_UPDATE_ON_START=true"
      - "ETS_SERVER_NAME=xxx"
      - "ETS_SERVER_PASSWORD=xxx"
#      - "ETS_SERVER_LOGON_TOKEN=xxx"
      - "ETS_SERVER_PLAYER_DAMAGE=false"
      - "ETS_SERVER_HIDE_COLLIDING=false"
      - "ETS_SERVER_SERVICE_NO_COLLISION=true"
      - "ETS_SERVER_MODERATORS=xxx"
```
